name: Egocentric
run-name: ${{ github.actor }} is testing out exercise 2
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
	Testing Q2:
		runs-on: macos-latest
		steps:
			- name: My name in README
			  run: |
			    if ! grep "Simona" README.md; then
			       echo "README doesn't contain Simona."
			       exit 1
			    fi