name: L06_Q2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest 
    steps:
      - name: check repo
        uses: actions/checkout@v3
      - name: My name in README
        run: |
          if ! grep -q "Simona" README.md; then
            echo "README doesn't contain 'Simona'."
            exit 1
          fi
